version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=password
    
  postgres: 
    image: 'postgres:latest' 
    restart: always 
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
