name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: docker build -t flask:latest .
  deploy:
    runs-on: build
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy docker image for flask on VM
        run: |
            docker login docker.io --username sverrek --password ${{ secrets.DOCKERHUB_PASSWORD }}
            docker stop $(docker ps -aq) && docker rm $(docker ps -aq)
            docker system prune -af
            docker pull docker.io/sverrek/flask:latest
            docker compose up -d

 
